config/routes.rb
Emerald::Application.routes.draw do
  
  resources :customer_information_control_systems

  resources :db2s

  resources :applications

  resources :customers

  resources :information_management_systems

  resources :sysplex_lpars

  resources :sysplexes

  resources :notifications

  resources :locations

  resources :machine_locs

  resources :cpus

  resources :machine_lpars

  resources :mods

  resources :machine_configs

  resources :capacities

  resources :lpar_configs

  devise_for :users

  resources :machines

  resources :lpars

  resources :ziips
  
  get "static_pages/home", :as => "home"

  get "static_pages/reports", :as => "reports"
  
  get "static_pages/ziipreport", :as => "ziipreport"
  
  get "static_pages/cpureport", :as => "cpureport"

  get "static_pages/configuration", :as => "configuration"

  get "static_pages/documents", :as => "documents"

  get "static_pages/about", :as => "about"
  
  get "static_pages/storageLayout", :as => "storageLayout"
    
  get "static_pages/dconfig", :as => "dconfig"
  
  get "static_pages/rspec_output", :as => "rspec"
  
  get "static_pages/uploadcsv", :as => "uploadcsv"
  
  get "static_pages/emerald", :as => "emerald"

  match 'ziips/:id/custom' => 'ziips#custom', :as => "ziips_custom"
  match 'ziips/zcustgraph' => 'ziips#zcustgraph', :as => "zcustgraph"
  match 'ziips/:id/canned' => 'ziips#canned', :as => "ziips_canned"
  match 'ziips/:id/twoweekavg' => 'ziips#twoweekavg', :as => "twoweekavg"
  match 'ziips/:id/twoweektot' => 'ziips#twoweektot', :as => "twoweektot"
  match 'ziips/:id/monAvg' => 'ziips#monAvg', :as => "monAvg"
  match 'ziips/:id/peaks' => 'ziips#peaksGraph', :as => "peaks"
  match 'ziips/:id/:lpar/all' => 'ziips#all', :as => "ziips_all"
  match 'ziips/:id/:name/allAvg' => 'ziips#allavg', :as => "ziips_allAvg"
  match 'ziips/:id/dayAverages' => 'ziips#dayAverages', :as => "dayAverages"
  
  match 'cpus/:id/:lpar/all' => 'cpus#all', :as => "cpus_all"  
  match 'cpus/:id/custom' => 'cpus#custom', :as => "cpus_custom"
  match 'cpus/:id/:name/allBox' => 'cpus#allBox', :as => "cpus_allBox"
  match 'cpus/:id/canned' => 'cpus#canned', :as => "cpus_canned"
  match 'cpus/mefbd' => 'cpus#mefbd', :as => "mefbd"
  match 'cpus/mefbdc' => 'cpus#mefbdc', :as => "mefbdc"
  match 'cpus/:id/avgday' => 'cpus#avgday', :as => "avgday"
  match 'cpus/custgraph' => 'cpus#custgraph', :as => "custgraph"
  
  match 'ziips/:id/total' => 'ziips#ztotal'
  match 'ziips/:id/total2' => 'ziips#ztotal2'
  match 'ziips/:id/hour' => 'ziips#zHour'
  match 'ziips/:id/:lpar/zall' => 'ziips#zAll'
  match 'ziips/:machine_id/zallavg' => 'ziips#zAllAvg'
  match 'ziips/:id/zday' => 'ziips#zday'
  
  match 'cpus/:id/total' => 'cpus#ctotal'
  match 'cpus/:id/:lpar/call' => 'cpus#cAll'
  match 'cpus/:id/:lpar/custom' => 'cpus#custom'
  match 'cpus/:machine_id/allCec' => 'cpus#allCec'
  match 'cpus/:machine_id/totBox' => 'cpus#totBox'









  root :to => 'static_pages#home'


end

app/models/cpu.rb
class Cpu < ActiveRecord::Base
  require "Date.rb"
  require 'csv'
  
  establish_connection :smfdata
  
  attr_accessor :lpars, :maxMips, :includeWeights, :totalMips, :timeBands, :month, :from, :to, :graphtype, :months, :machines, :increment, :data
  attr_accessible :datetime, :id, :mips, :smfid, :lpars, :maxMips, :includeWeights, :totalMips, :timeBands, :month, :from, :to, :graphtype, :months, :machines, :increment, :data
  
  belongs_to :machine
  by_star_field :datetime
  
  def after_initialize 
    self.lpars ||= {}
    self.machines ||= {}
  end
  
  #Parse a cpudata csv file
  def self.parseCSV(filename)
    CSV.foreach('/home/ftp/mips/' + filename, col_sep: ',') do |row|
      date = row[1]
      month = date[0,2]
      day = date[3,2]
      year = date[6,2].to_i + 2000
      date = year.to_s + "-" + month + "-" + day + " " + row[2]
      Cpu.create(datetime: date, smfid: row[0], mips: row[3])
    end
      File.delete('/home/ftp/mips/' + filename) 
  end
  
  #Convert a datetime to epoch time for Highcharts. format "YYYY-MM-DD HH:MM:SS"
  def self.datetime_to_epoch(datetime)
    Time.local(datetime.strftime('%Y').to_i, datetime.strftime('%m').to_i, datetime.strftime('%d').to_i, datetime.strftime('%H').to_i, datetime.strftime('%M').to_i, datetime.strftime('%S').to_i).to_i * 1000
  end
  
  #Find each LPARs cpu or MIPS peak use. smfid, max, and average returned.
  def self.findLPARpeaks(mid)
    @Machine = Machine.find(mid)
    Cpu.find(:all, :group => "smfid", :select => "smfid, max(mips) as max, AVG(mips) as average", :conditions => ['smfid in (?)', @Machine.lpars.map(&:smfid)])
  end
  
  #Find the peak period of the BOX and how much MIPS it is using total. datetime and peak returned.
  def self.findBOXpeaks(mid)
    @Machine = Machine.find(mid)
    Cpu.find(:all, :group => "date(datetime),time(datetime)", :select => "datetime ,sum(mips) as peak", :order => "peak DESC", :conditions => ['smfid in (?)', @Machine.lpars.map(&:smfid)])
  end
  
  #Gets the mefbd totals by LPAR and month.
  def self.mefbdTotalsByLPAR(lid,month)
    @totals = Array.new
    (Cpu.between(Date.parse(month).beginning_of_month.previous_business_day('us'),Date.parse(month).beginning_of_month.next_business_day('us') ).where(:smfid => Lpar.find(lid).smfid).group("date(datetime),time(datetime)").select("datetime, mips")).each do |i|
      @totals.push([Cpu.datetime_to_epoch(i.datetime),i.mips])
    end
    return @totals
  end
  #Gets the mefbd totals by BOX total and month.
  def self.mefbdTotalsByBox(mid,month)
    @totals = Array.new
    @Machine = Machine.find(mid)
    Cpu.between(Date.parse(month).beginning_of_month.previous_business_day('us'),Date.parse(month).beginning_of_month.next_business_day('us') ).find(:all, :group => "date(DateTime),time(DateTime)", :select => "datetime, sum(mips) as mips", :conditions => ['smfid in (?)', @Machine.lpars.map(&:smfid)]).each do |i|
      @totals.push([Cpu.datetime_to_epoch(i.datetime),i.mips])
    end
    return @totals
  end
  
  #Find the average MIPS the BOX uses.
  def self.findBOXaverage(mid)
    @Machine = Machine.find(mid)
    @mipsSum = Cpu.find(:all, :group => "date(DateTime),time(DateTime)", :select => "sum(mips) as average", :conditions => ['smfid in (?)', @Machine.lpars.map(&:smfid)])
    sum = 0
    @mipsSum.each_with_index do |m,i|
      sum += @mipsSum[i].average.to_f 
    end
    
    return (sum / @mipsSum.count).round  
  end
end

app/controllers/cpus_controller.rb
class CpusController < ApplicationController
  require 'active_support/core_ext/numeric/time'
  require "Date.rb"
  
  # GET /cpus
  # GET /cpus.json
  def index
    @cpus = Cpu.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cpus }
    end
  end

  # GET /cpus/1
  # GET /cpus/1.json
  def show
    @cpu = Cpu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cpu }
    end
  end

  # GET /cpus/new
  # GET /cpus/new.json
  def new
    @cpu = Cpu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cpu }
    end
  end

  # GET /cpus/1/edit
  def edit
    @cpu = Cpu.find(params[:id])
  end

  # POST /cpus
  # POST /cpus.json
  def create
    @cpu = Cpu.new(params[:cpu])

    respond_to do |format|
      if @cpu.save
        format.html { redirect_to @cpu, notice: 'Cpu was successfully created.' }
        format.json { render json: @cpu, status: :created, location: @cpu }
      else
        format.html { render action: "new" }
        format.json { render json: @cpu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cpus/1
  # PUT /cpus/1.json
  def update
    @cpu = Cpu.find(params[:id])

    respond_to do |format|
      if @cpu.update_attributes(params[:cpu])
        format.html { redirect_to @cpu, notice: 'Cpu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cpu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cpus/1
  # DELETE /cpus/1.json
  def destroy
    @cpu = Cpu.find(params[:id])
    @cpu.destroy

    respond_to do |format|
      format.html { redirect_to cpus_url }
      format.json { head :no_content }
    end
  end
  
   def cAll
    @cAll = Cpu.where(:smfid => params[:lpar]).group("datetime").select("datetime, mips")
      respond_to do |format|
      #format.html # show.html.erb
      format.json { render json: @cAll }
    end
  end
  
  def totBox
    @machine = Machine.includes(:lpars).where(:id => params[:machine_id])
    @totBox= Cpu.find(:all, :group => "date(DateTime),time(DateTime)", :select => "datetime, sum(mips) as mips", :conditions => ['smfid in (?)', @machine[0].lpars.map(&:smfid)])
      respond_to do |format|
      #format.html # show.html.erb
      format.json { render json: @totBox }
    end  
  end
  
  def allBox
    #placeholder
  end

  def all 
    #placeholder
  end
  
  def custom
    gon.startDate = Cpu.first(order: 'datetime asc').datetime 
    @cpus = Cpu.new  
  end
  
  def canned
    gon.startDate = Cpu.first(order: 'datetime asc').datetime
    @lpars = Location.lparList(params[:location])
    @machines = Location.find(params[:location]).machines
    @cpus = Cpu.new
  end
  
  def mefbdc
    @cpus = Cpu.new
  end
  
  def custgraph
  end
  
  def avgday
    @cpus = Cpu.new
    params[:cpu][:lpars] = params[:cpu][:lpars].delete_if{ |x| x.empty? }
  end
  
  def mefbd
    @lpars = Array.new
    @machines = Array.new
    
    #For a Rails bug. Puts one blank array slot.
    params[:cpu][:lpars] = params[:cpu][:lpars].delete_if{ |x| x.empty? }
    params[:cpu][:machines] = params[:cpu][:machines].delete_if{ |x| x.empty? }
    
    #Create my LPARS array the user selected
      params[:cpu][:lpars].each do |lpid|
        @lpars.push(Lpar.find(lpid))
      end
      
    #Create the machines array based on the LPARS selected.
      params[:cpu][:machines].each do |m|
        @machines.push(Machine.find(m.to_i))
      end
      
    #Get only unique machines from machines.
    #@machines = @machines.inject([]) { |result,h| result << h unless result.include?(h); result }
    
  end
end

app/helpers/cpus_helper.rb
module CpusHelper
end

app/views/cpus/_avgday.html.erb
<script>
$(function() {
  $.datepicker.setDefaults({dateFormat: "yy-mm-dd"});
  $("#cpudbdfrom").datepicker({
    minDate: gon.startDate,
    maxDate: -1,
    defaultDate: "-1d",
    changeMonth: true,
    changeYear: true,
    numberOfMonths: 1,
	    onSelect: function(selectedDate) {
	      $("#cpudbdto").datepicker("option", "minDate", selectedDate);
	     	}
     });

  $("#cpudbdto").datepicker({
    minDate: "#cpudbdfrom",
    maxDate: -1,
    defaultDate: "-1d",
    changeMonth: true,
    changeYear: true,
    numberOfMonths: 1,
	    onSelect: function(selectedDate) {
	      $("#cpudbdfrom").datepicker("option", "maxDate", selectedDate);
	     }
    });
});
</script>
<h3>Day Averages</h3>
Select length of time:<br><br>
<%= simple_form_for(@cpus, :url => avgday_path(1)) do |f| %>
	From:
	<%= f.datepicker :from, id: "cpudbdfrom" %> To:
	<%= f.datepicker :to, id: "cpudbdto" %>
	<br><br>
	Select multiple by holding down "Ctrl".
	<br><br>
	<%= f.input :lpars, :collection => Location.lparList(params[:location]) , :input_html => { :multiple => true, :class => "input-large", :size => "10" }%>
	<br>
	<%= f.input :machines, :collection => Location.find(params[:location]).machines , :input_html => { :multiple => true, :class => "input-large", :size => "5" }%>
	<br>	
  <div class="actions">
    <%= f.submit "Graph", :class => 'btn btn-primary' %>
    <%= submit_tag 'Clear', :type => :reset, :class => "btn btn-danger" %>
  </div>
<% end %>

app/views/cpus/_custom.html.erb
<script>
$(function() {
  $.datepicker.setDefaults({dateFormat: "yy-mm-dd"});
  $("#cpudbdfrom").datepicker({
    minDate: gon.startDate,
    maxDate: -1,
    defaultDate: "-1d",
    changeMonth: true,
    changeYear: true,
    numberOfMonths: 1,
	    onSelect: function(selectedDate) {
	      $("#cpudbdto").datepicker("option", "minDate", selectedDate);
	     	}
     });

  $("#cpudbdto").datepicker({
    minDate: "#cpudbdfrom",
    maxDate: -1,
    defaultDate: "-1d",
    changeMonth: true,
    changeYear: true,
    numberOfMonths: 1,
	    onSelect: function(selectedDate) {
	      $("#cpudbdfrom").datepicker("option", "maxDate", selectedDate);
	     }
    });
});
</script>
<h3>Custom Graph</h3>
Create a custom graph below. NOTE! THIS DATA CAN BE VERY CPU INTENSE! BE CAREFUL.<br>

<br>
<%= simple_form_for(@cpus, :url => custgraph_path) do |f| %>
	From:
	<%= f.datetime_picker :from, id: "cpudbdfrom" %> To:
	<%= f.datetime_picker :to, id: "cpudbdfrom" %>
	<br><br>
	Data as <%= f.select :data, options_for_select(DATA) %>
	<br><br>
    Increment as <%= f.select :increment, options_for_select(INCTYPES) %>
    <br><br>
	<strong>Select multiple by holding down "Ctrl"</strong>
	<br><br>
	<%= f.input :lpars, :collection => Location.lparList(params[:location]) , :input_html => { :multiple => true, :class => "input-large", :size => "10" }%>
	<br>
	<%= f.input :includeWeights, :label => 'Include LPAR Weight(s)', :as => :boolean %>
	<br>
	<%= f.input :machines, :collection => Location.find(params[:location]).machines , :input_html => { :multiple => true, :class => "input-large", :size => "5" }%>
	<br>
	<%= f.input :maxMips, :label => 'Include Maximum CEC MIPS', :as => :boolean %>
	<br>
	Graph Type
	<%= f.select :graphtype, options_for_select(GRAPHTYPES) %>
	<br><br>	
  <div class="actions">
    <%= f.submit "Graph", :class => 'btn btn-primary' %>
    <%= submit_tag 'Clear', :type => :reset, :class => "btn btn-danger" %>
  </div>
<% end %>

app/views/cpus/_mefbdc.erb
<h3>ME/FBD Comparison</h3>
A month end and first business day comparison report based upon selected data below.<br><br>

<%= simple_form_for(@cpus, :url => mefbdc_path) do |f| %>
	<%= f.input :months, :collection => Cpu.pluck("DATE_FORMAT(datetime, '%M, %Y')").uniq, :input_html => { :multiple => true, :class => "input-large", :size => "5" }%>	
  	<%= f.input :lpars, :label => 'LPARs', :collection => @lpars, :input_html => { :multiple => true, :class => "input-large", :size => "10" }%>
	<span class="help-block label label-info" style="width: 380px">Select multiple by holding down "Ctrl" then making selections.</span>
	<%= f.input :machines, :collection => @machines, :input_html => { :multiple => true, :class => "input-large", :size => "5" }%>
	<%= f.input :maxMips, :label => 'Max MIPS Line', :as => :boolean %>
	<%= f.input :includeWeights, :label => 'LPAR Weight Line', :as => :boolean %>
	<br>
  <div class="actions">
    <%= f.submit "Graph ME/FBD comparison", :class => 'btn btn-primary' %>
    <%= submit_tag 'Clear', :type => :reset, :class => "btn btn-danger" %>
  </div>
<% end %>

app/views/cpus/all.html.erb
​<script>
$(function () {
    $.get("/cpus/1/<%= params[:lpar] %>/call", {}, function (data) {
        var arr = new Array();
        $.each(data, function (index, obj) {
            arr.push([
            Date.UTC(
            obj.datetime.substring(0, 4),
            obj.datetime.substring(5, 7) - 1,
            obj.datetime.substring(8, 10),
            obj.datetime.substring(11, 13),
            obj.datetime.substring(14, 16),
            obj.datetime.substring(17, 19)), obj.mips]);
        });
        window.chart = new Highcharts.StockChart({
            chart: {
                renderTo: 'container'
            },
            rangeSelector: {
                buttons: [{
                    type: 'hour',
                    count: 1,
                    text: '1h'
                }, {
                    type: 'day',
                    count: 3,
                    text: '3d'
                }, {
                    type: 'week',
                    count: 1,
                    text: '1w'
                }, {
                    type: 'month',
                    count: 1,
                    text: '1m'
                }, {
                    type: 'month',
                    count: 6,
                    text: '6m'
                }, {
                    type: 'year',
                    count: 1,
                    text: '1y'
                }, {
                    type: 'all',
                    text: 'All'
                }],
                selected: 2
            },
            plotOptions: {
                area: {
                    fillColor: {
                        linearGradient: [0, 0, 0, 300],
                        stops: [
                            [0, Highcharts.getOptions().colors[0]],
                            [1, 'rgba(2,0,0,0)']
                        ]
                    },
                    lineWidth: 1,
                    marker: {
                        enabled: false,
                        states: {
                            hover: {
                                enabled: true,
                                radius: 5
                            }
                        }
                    },
                    shadow: false,
                    states: {
                        hover: {
                            lineWidth: 1
                        }
                    }
                }
            },
            title: {
                text: '<%= params[:lpar] %> - MIPS'
            },
            xAxis: {
                tickInterval: 24 * 3600 * 1000,
                maxZoom: 1 * 24 * 3600000
            },
            yAxis: {
                title: {
                    text: "MIPS Used"
                },
                min: 0
            },
            series: [{
                name: '<%= params[:lpar] %>',
                data: arr,
                tooltip: {
                    valueDecimals: 2
                },
                dataGrouping: {
                    enabled: true,
                }
            }]
        });
    })
});
</script>
<div id="container" style="height: width:1200px; height:600px;"></div>​

app/views/cpus/allBox.erb
​<script>
$(function() {
	    	$('div#loading').fadeIn("slow"); 
	    	$.get("/cpus/<%= params[:id] %>/totBox",{},function(data){
		      				var arr = new Array();
					      	$.each(data, function(index,obj) {
					               		arr.push([ 
					               			Date.UTC(
					               				obj.datetime.substring(0,4),
					               				obj.datetime.substring(5,7)-1,
					               				obj.datetime.substring(8,10),
					               				obj.datetime.substring(11,13),
					               				obj.datetime.substring(14,16),
					               				obj.datetime.substring(17,19)
					               			),obj.mips]);
					      	});
			      	 window.chart = new Highcharts.StockChart({
			            chart : {
			                renderTo : 'container'
			            },
					 rangeSelector: {
					        buttons: [{
								type : 'hour',
								count : 1,
								text : '1h'
							}, {
					            type: 'day',
					            count: 3,
					            text: '3d'
					        }, {
					            type: 'week',
					            count: 1,
					            text: '1w'
					        }, {
					            type: 'month',
					            count: 1,
					            text: '1m'
					        }, {
					            type: 'month',
					            count: 6,
					            text: '6m'
					        }, {
					            type: 'year',
					            count: 1,
					            text: '1y'
					        }, {
					            type: 'all',
					            text: 'All'
					        }],
					        selected: 2
					    },
					    plotOptions: {
							area: {
								fillColor: {
									linearGradient: [0, 0, 0, 300],
									stops: [
										[0, Highcharts.getOptions().colors[0]],
										[1, 'rgba(2,0,0,0)']
									]
								},
								lineWidth: 1,
								marker: {
									enabled: false,
									states: {
										hover: {
											enabled: true,
											radius: 5
										}
									}
								},
								shadow: false,
								states: {
									hover: {
										lineWidth: 1
									}
								}
							}
						},
			            title : {
			                text : '<%= params[:name] %> Total MIPS Used (30min intervals)'
			            },
			            xAxis : { tickInterval:  24 * 3600 * 1000,
			            		  maxZoom : 3600000 },
			            yAxis : { title: { text: "MIPS" }, min: 0 },
			            series : [{
			                name : '<%= params[:name] %>',
			                data : arr,
					        tooltip: {
		                    valueDecimals: 2
		                },
		                	dataGrouping : {
                    			enabled: false,
                    		}
			            }]
			        });
           		})
           		$('div#loading').fadeOut("slow"); 
           });
</script>
<div id="loading" align="center"><strong><h1>Loading</h1></strong></div>
<div id="container" style="height: width:1200px; height:600px;"></div>

app/views/cpus/avgday.html.erb
<script type="text/javascript">
$(function() {
		var mipsChart = new Highcharts.Chart({
			chart: { renderTo: "mipsChart", type: "column",
					 events: {
					 	load: function(){					 		
										<% params[:cpu][:lpars].each do |lpar| %>
								    	         $.get("/cpus/1/cday", {
								    	         	from: '<%= params[:cpu][:from] %>',
								    	         	to: '<%= params[:cpu][:to] %>',
										        	scope: '<%= Lpar.find(lpar).smfid %>'
										      	},function(data){
										      		var arr2 = new Array();
											      	$.each(data, function(index,obj) {
									               		arr2.push([Date.UTC(
									               				obj.datetime.substring(0,4),
									               				obj.datetime.substring(5,7)-1,
									               				obj.datetime.substring(8,10),
									               				obj.datetime.substring(11,13),
									               				obj.datetime.substring(14,16),
									               				obj.datetime.substring(17,19)
									               			),parseFloat(obj.average)]);
											      	});
											      	console.log(arr2);
										      	mipsChart.addSeries({
										      		name: "<%= Lpar.find(lpar).name %>",		      		
								                	data: arr2
								            	});
								           })
								    	<% end %>
						    			}
						   }
				   },
			title: { text: "MIPS Average by Day" },
			xAxis: { type: "datetime",
					 dateTimeLabelFormats: {
        				day: '%b %e %Y'   
    					},
					 tickInterval: 24 * 3600 * 1000,
		    		 labels: {
		    			rotation:-45,
		    		    align: 'right'
		    			} 
		    		},
			yAxis: { title: { text: "Average MIPS Used" }},
			series: []
	});	
});
</script>
<div id="mipsChart" style="width:1200px; height:600px;"></div>

app/views/cpus/canned.html.haml
- model_class = Cpu
.page-header
  %h1 Canned CPU Reports #{Location.find(params[:location]).name}
.tabbable.tabs-left
  %ul.nav.nav-tabs
    %li.active
      %a{"data-toggle" => "tab", href: "#mefbd"} ME/FBD
    %li
      %a{"data-toggle" => "tab", href: "#mefbdc"} ME/FBD compare
    %li
      %a{"data-toggle" => "tab", href: "#2weekavg"} 2 Week Avg
    %li
      %a{"data-toggle" => "tab", href: "#dayavg"} Avg by Day
  .tab-content
    #mefbd.tab-pane.active
      = render partial: 'mefbd'
    #mefbdc.tab-pane
      = render partial: 'mefbdc'
    #2weekavg.tab-pane
      2 Week Avg - Under Construction
    #dayavg.tab-pane
      = render partial: 'avgday'

app/views/cpus/custom.html.haml
= render :partial => 'custom'

app/views/cpus/edit.html.haml
- model_class = Cpu
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/cpus/index.html.haml
- model_class = Cpu
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:datetime)
      %th= model_class.human_attribute_name(:smfid)
      %th= model_class.human_attribute_name(:mips)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @cpus.each do |cpu|
      %tr
        %td= link_to cpu.id, cpu_path(cpu)
        %td= cpu.datetime
        %td= cpu.smfid
        %td= cpu.mips
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_cpu_path(cpu), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), cpu_path(cpu), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'
= will_paginate @cpus, :renderer => BootstrapPagination::Rails
= link_to t('.new', :default => t("helpers.links.new")), new_cpu_path, :class => 'btn btn-primary'

app/views/cpus/new.html.haml
- model_class = Cpu
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/cpus/show.html.haml
- model_class = Cpu
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:datetime) + ':'
  %br
  = @cpu.datetime
%p
  %strong= model_class.human_attribute_name(:smfid) + ':'
  %br
  = @cpu.smfid
%p
  %strong= model_class.human_attribute_name(:mips) + ':'
  %br
  = @cpu.mips

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), cpus_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_cpu_path(@cpu), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), cpu_path(@cpu), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'