config/routes.rb
Emerald::Application.routes.draw do
  
  resources :customer_information_control_systems

  resources :db2s

  resources :applications

  resources :customers

  resources :information_management_systems

  resources :sysplex_lpars

  resources :sysplexes

  resources :notifications

  resources :locations

  resources :machine_locs

  resources :cpus

  resources :machine_lpars

  resources :mods

  resources :machine_configs

  resources :capacities

  resources :lpar_configs

  devise_for :users

  resources :machines

  resources :lpars

  resources :ziips
  
  get "static_pages/home", :as => "home"

  get "static_pages/reports", :as => "reports"
  
  get "static_pages/ziipreport", :as => "ziipreport"
  
  get "static_pages/cpureport", :as => "cpureport"

  get "static_pages/configuration", :as => "configuration"

  get "static_pages/documents", :as => "documents"

  get "static_pages/about", :as => "about"
  
  get "static_pages/storageLayout", :as => "storageLayout"
    
  get "static_pages/dconfig", :as => "dconfig"
  
  get "static_pages/rspec_output", :as => "rspec"
  
  get "static_pages/uploadcsv", :as => "uploadcsv"
  
  get "static_pages/emerald", :as => "emerald"

  match 'ziips/:id/custom' => 'ziips#custom', :as => "ziips_custom"
  match 'ziips/zcustgraph' => 'ziips#zcustgraph', :as => "zcustgraph"
  match 'ziips/:id/canned' => 'ziips#canned', :as => "ziips_canned"
  match 'ziips/:id/twoweekavg' => 'ziips#twoweekavg', :as => "twoweekavg"
  match 'ziips/:id/twoweektot' => 'ziips#twoweektot', :as => "twoweektot"
  match 'ziips/:id/monAvg' => 'ziips#monAvg', :as => "monAvg"
  match 'ziips/:id/peaks' => 'ziips#peaksGraph', :as => "peaks"
  match 'ziips/:id/:lpar/all' => 'ziips#all', :as => "ziips_all"
  match 'ziips/:id/:name/allAvg' => 'ziips#allavg', :as => "ziips_allAvg"
  match 'ziips/:id/dayAverages' => 'ziips#dayAverages', :as => "dayAverages"
  
  match 'cpus/:id/:lpar/all' => 'cpus#all', :as => "cpus_all"  
  match 'cpus/:id/custom' => 'cpus#custom', :as => "cpus_custom"
  match 'cpus/:id/:name/allBox' => 'cpus#allBox', :as => "cpus_allBox"
  match 'cpus/:id/canned' => 'cpus#canned', :as => "cpus_canned"
  match 'cpus/mefbd' => 'cpus#mefbd', :as => "mefbd"
  match 'cpus/mefbdc' => 'cpus#mefbdc', :as => "mefbdc"
  match 'cpus/:id/avgday' => 'cpus#avgday', :as => "avgday"
  match 'cpus/custgraph' => 'cpus#custgraph', :as => "custgraph"
  
  match 'ziips/:id/total' => 'ziips#ztotal'
  match 'ziips/:id/total2' => 'ziips#ztotal2'
  match 'ziips/:id/hour' => 'ziips#zHour'
  match 'ziips/:id/:lpar/zall' => 'ziips#zAll'
  match 'ziips/:machine_id/zallavg' => 'ziips#zAllAvg'
  match 'ziips/:id/zday' => 'ziips#zday'
  
  match 'cpus/:id/total' => 'cpus#ctotal'
  match 'cpus/:id/:lpar/call' => 'cpus#cAll'
  match 'cpus/:id/:lpar/custom' => 'cpus#custom'
  match 'cpus/:machine_id/allCec' => 'cpus#allCec'
  match 'cpus/:machine_id/totBox' => 'cpus#totBox'









  root :to => 'static_pages#home'


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @notifications = Notification.all 
  end
  
  def reports
    #Gather the locations from the database
    @locations = Location.all
    
    #Check if the location contains machines.
    @locations.delete_if{ |x| !x.machine_locs.exists? }
  end
  
  def ziipreport    
    #Get the locations machines.
    @machines = Location.find(params[:location]).machines
    
    #Make sure the machine has a ZIIP. If not, dont even bother querying for information.
    @machines.delete_if{ |x| x.machineConfig.ziip <= 0 }
  end
   
  def cpureport
  end

  def configuration
  end

  def documents
    @locations = Location.all
    
    #Check if the location contains machines.
    @locations.delete_if{ |x| !x.machine_locs.exists? }
  end

  def about
    require 'socket'
    @host = Socket.gethostname
  end
  
  def storageLayout
    #Get the locations machines.
    @machineList = Location.find(params[:location]).machines
  end
  
  def dconfig
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  #create document pill if location has machines.
  def document_pill(location)
  capture_haml do
   location.machines.each do |m|     
       if(!m.machineConfig.nil?)           
               haml_tag :div, id: "box" do
                   haml_tag :h3 do
                       haml_concat "#{location.name}"
                     end
                   haml_tag :ul, class: "nav nav-list" do
                      haml_concat documents_info(location)
                   end
               end
            end
         break
        end  
    end
  end
  
  #create the report pill if the location contains report data.
  def report_pill(location)
    capture_haml do
     if(ziips_info(location) && cpu_info(location))
       haml_tag :div, id: "box" do  
         haml_tag :h3 do
           haml_concat "#{location.name}"
         end    
             haml_tag :ul, class: "nav nav-list" do 
               haml_concat ziips_info(location)
               haml_concat cpu_info(location)
             end
       end
      end
     end
  end
  
  #Does a location have ZIIP information in the database? If so display it.
  def ziips_info(location)    
    if(contain_ziip_data(location))            
              capture_haml do
                    haml_tag :li, "ZIIP", class: "nav-header"
                    haml_tag :li do
                      haml_concat link_to "ZIIP Stats", ziipreport_path(location: location.id)
                      #haml_concat link_to "ZIIP Custom", ziips_custom_path(1, location: location.id)
                      haml_concat link_to "ZIIP Canned", ziips_canned_path(1, location: location.id)
                    end

                  haml_tag :div, id: "accordion#{location.id}", class: "accordion" do
                    haml_tag :div, class: "accordion-group" do
                      haml_tag :div, class: "accordion-heading" do
                        haml_tag :a, class: "accordion-toggle", "data-parent" => "#accordion#{location.id}", "data-toggle" => "collapse", "href" => "#collapse#{location.id}" do
                          haml_concat "All Data"
                        end
                      end
                      
                      haml_tag :div, class: "accordion-body collapse", id: "collapse#{location.id}" do
                        haml_tag :div, class: "accordian-inner" do
                          haml_tag :ul, class: "nav nav-list" do
                            location.machines.each_with_index do |m,x|
                             if(m.machineConfig) 
                              if(m.machineConfig.ziip)
                                haml_tag :li do
                                  haml_concat link_to m.name, ziips_allAvg_path(m.id, m.name)
                                end
                              end
                             end
                              location.machines[x].lpars.each do |lpar|
                                if(Ziip.exists?(LPAR: lpar.name))
                                  haml_tag :li do
                                    haml_concat link_to lpar.name, ziips_all_path(1, lpar.name)
                                  end
                                end
                              end
                                                         
                            end
                          end
                        end
                        
                      end
                    end
                    
                  end
              end
        end
    end
  
  #Does a location have CPU information in the database (MIPS)? If so display it.  
  def cpu_info(location)    
    if(contain_cpu_data(location))            
              capture_haml do
                    haml_tag :li, "CPU", class: "nav-header"
                    haml_tag :li do
                      haml_concat link_to "CPU Stats", cpureport_path(location: location.id)
                      #haml_concat link_to "CPU Custom", cpus_custom_path(1, location: location.id)
                      haml_concat link_to "CPU Canned", cpus_canned_path(1, location: location.id)
                    end

                  haml_tag :div, id: "accordion2#{location.id}", class: "accordion" do
                    haml_tag :div, class: "accordion-group" do
                      haml_tag :div, class: "accordion-heading" do
                        haml_tag :a, class: "accordion-toggle", "data-parent" => "#accordion2#{location.id}", "data-toggle" => "collapse", "href" => "#collapse2#{location.id}" do
                          haml_concat "All Data"
                        end
                      end
                      
                      haml_tag :div, class: "accordion-body collapse", id: "collapse2#{location.id}" do
                        haml_tag :div, class: "accordian-inner" do
                          haml_tag :ul, class: "nav nav-list" do
                            location.machines.each_with_index do |m,x|
                              haml_tag :li do
                                if(Cpu.exists?(['smfid in (?)', m.lpars.map(&:smfid)]))
                                  haml_concat link_to m.name, cpus_allBox_path(m.id, m.name)
                                end
                             end
                              location.machines[x].lpars.each do |lpar|
                                if(Cpu.exists?(smfid: lpar.smfid))
                                  haml_tag :li do
                                    haml_concat link_to lpar.name, cpus_all_path(1, lpar.smfid)
                                  end
                                end
                              end
                            end
                          end
                        end
                        
                      end
                    end
                    
                  end
              end
        end
    end
    
    #Display storage layout links and DCONFIG links
    def documents_info(location)
      capture_haml do
        haml_tag :li, "CPU", class: "nav-header"
          haml_tag :li do
            haml_concat link_to "Storage Layout", storageLayout_path(location: location.id)
            haml_concat link_to "DCONFIG", dconfig_path
          end
       end
    end
    
    #Checks if a location has machines with ZIIP data.
    def contain_ziip_data(location)
      location.machines.each do |m|
        if(m.machineConfig)
            if(m.machineConfig.ziip)
              return true
            else
              return false
            end
         else
           return false
         end
      end
    end
    
    #Checks if a location has machines with CPU data.
    def contain_cpu_data(location)
      location.machines.each do |m|
        if(m.machineConfig)
            if(Cpu.exists?(['smfid in (?)', m.lpars.map(&:smfid)]))
              return true
            else
              return false
            end
         else
           return false
         end
      end
    end

end

app/views/static_pages/about.haml
.page-header
  %h1 About
%p
Emerald is a capacity planning, reporting, and document creation tool.
%p
  CSV data
  %br
  Host: 
  = @host
  %br
  Port: 21
#footer{:align => "center"}
  %a{:href => "mailto:Paul.Meier@fisglobal.com"} Contact​

app/views/static_pages/configuration.haml
.page-header
  %h1 Configuration
#accordion2.accordion
  .accordion-group
    .accordion-heading
      %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseOne"}
        Machines
    #collapseOne.accordion-body.collapse
      .accordion-inner
        %ul.nav.nav-pills.nav-stacked
          %li= link_to "Machines", machines_path
          %li= link_to "Configurations", machine_configs_path
          %li= link_to "Machine LPARs", machine_lpars_path
          %li= link_to "Capacity", capacities_path
          %li= link_to "Models", mods_path
  .accordion-group
    .accordion-heading
      %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseTwo"}
        LPARs
    #collapseTwo.accordion-body.collapse
      .accordion-inner
        %ul.nav.nav-pills.nav-stacked
          %li= link_to "LPARs", lpars_path
          %li= link_to "Configurations", lpar_configs_path
  .accordion-group
    .accordion-heading
      %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseThree"}
        Sysplex
    #collapseThree.accordion-body.collapse
      .accordion-inner
        %ul.nav.nav-pills.nav-stacked
          %li= link_to "Sysplex", sysplexes_path
          %li= link_to "Sysplex LPARs", sysplex_lpars_path
  .accordion-group
    .accordion-heading
      %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseFour"}
        IMS
    #collapseFour.accordion-body.collapse
      .accordion-inner
        %ul.nav.nav-pills.nav-stacked
          %li= link_to "IMS", information_management_systems_path
  .accordion-group
    .accordion-heading
      %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseFive"}
        Customers
    #collapseFive.accordion-body.collapse
      .accordion-inner
        %ul.nav.nav-pills.nav-stacked
          %li= link_to "Customers", customers_path
  .accordion-group
    .accordion-heading
      %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseSix"}
        Locations
    #collapseSix.accordion-body.collapse
      .accordion-inner
        %ul.nav.nav-pills.nav-stacked
          %li= link_to "Locations", locations_path
          %li= link_to "Machine Locations", machine_locs_path
  .accordion-group
    .accordion-heading
      %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseSeven"}
        Applications
    #collapseSeven.accordion-body.collapse
      .accordion-inner
        %ul.nav.nav-pills.nav-stacked
          %li= link_to "Applications", applications_path
  .accordion-group
    .accordion-heading
      %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseNine"}
        DB2s
    #collapseNine.accordion-body.collapse
      .accordion-inner
        %ul.nav.nav-pills.nav-stacked
          %li= link_to "DB2s", db2s_path
  .accordion-group
    .accordion-heading
      %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseTen"}
        CICS
    #collapseTen.accordion-body.collapse
      .accordion-inner
        %ul.nav.nav-pills.nav-stacked
          %li= link_to "CICS", customer_information_control_systems_path
  .accordion-group
    .accordion-heading
      %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseEight"}
        Report Data
    #collapseEight.accordion-body.collapse
      .accordion-inner
        %ul.nav.nav-pills.nav-stacked
          %li= link_to "ZIIP", ziips_path
          %li= link_to "CPU", cpus_path

app/views/static_pages/cpureport.html.haml
.page-header
  %h1 CPU Detailed Report
- Location.find(params[:location]).machines.each do |m|
  %h3= m.name
  %strong
    Name
  = m.name
  %br
  %strong
    Peak MIPS
  = Cpu.findBOXpeaks(m.id).first.peak.to_i
  %br
  %strong
    Peak Time
  = Cpu.findBOXpeaks(m.id).first.datetime.in_time_zone("Central Time (US & Canada)")
  %br
  %strong
    Average MIPS
  = Cpu.findBOXaverage(m.id)
  %table#minTable
    %thead
      %tr
        %th LPAR
        %th Peak
        %th Average
        %th MIPS Weight 
    %tbody
      - Cpu.findLPARpeaks(m.id).each do |l|
        %tr
          %td= l.smfid
          %td= l.max.round
          %td= l.average.round
          %td= LparConfig.weightMIPS(Lpar.find_by_smfid(l.smfid).id)
  %br

app/views/static_pages/data.html.haml
%h1 Data
#box
  %h3 Report Data
  %ul.nav.nav-pills.nav-stacked
    %li= link_to "ZIIP", ziips_path
    %li= link_to "CPU", cpus_path

app/views/static_pages/dconfig.html.erb
<style>
  #myCanvas {
    border: 1px solid #9C9898;
  }
  body {
    margin: 0px;
    padding: 50px 0px 0px 0px;
  }
</style>
    <script>
      window.onload = function() {
        var canvas = document.getElementById('myCanvas');
        var context = canvas.getContext('2d');
        var x = 20;
        var y = 40;
	<% (Machine.find(1).lpars.count).times.each_with_index do |i| %>
        context.beginPath();        
        context.rect( 20, x, 200, 100);
        context.fillStyle = '#FFFF00';
        context.fill();
        context.fillStyle = '#000000';
        context.fillText('<%= Machine.find(1).lpars[i].name %>', 25, y);
        context.fillText('<%= Machine.find(1).lpars[i].mid %>', 200, y);
        context.fillText('Customer Information', 25, y + 30);
        context.lineWidth = 2;
        context.strokeStyle = 'black';
        context.stroke();
        x = x + 100;
        y = y + 100;
    <% end %>
		
		x = 20;
        y = 40;
	<% (Machine.find(2).lpars.count).times.each_with_index do |i| %>
        context.beginPath();        
        context.rect( 880, x, 200, 100);
        context.fillStyle = '#FFFF00';
        context.fill();
        context.fillStyle = '#000000';
        context.fillText('<%= Machine.find(2).lpars[i].name %>', 885, y);
        context.fillText('<%= Machine.find(2).lpars[i].mid %>', 1060, y);
        context.fillText('Customer Information', 885, y + 30);
        context.lineWidth = 2;
        context.strokeStyle = 'black';
        context.stroke();
        x = x + 100;
        y = y + 100;
	<% end %>
      };

</script>
<canvas id="myCanvas" width="1100" height="1000"></canvas>Under Construction

app/views/static_pages/documents.haml
.page-header
  %h1 Documents
- @locations.each do |location|
  = document_pill(location)

app/views/static_pages/emerald.haml
.page-header
  %h1 Emerald Information
#box
  %h3 Emerald
  %ul.nav.nav-list
    %li.nav-header Documentation
    %li= link_to "Emerald API", "http://p21mcref01/eapi/"
    %li= link_to "Highcharts Reference", "http://api.highcharts.com/highcharts#chart"
    %li= link_to "Ruby-On-Rails Reference", "http://p21mcref01/rails-api/"
    %li= link_to "JQuery API", "http://api.jquery.com/"
    %li= link_to "RSPEC API", "http://rubydoc.info/gems/rspec-core/2.6.4/index"
    
    %li.nav-header Status Reports
    %li= link_to "Emerald Status", "http://p21mcref01/rspec_output.html"
    %li.nav-header Code History
    %li= link_to "Emerald History", "http://p21mcref01:1234/?p=.git;a=summary"
    
    


app/views/static_pages/home.html.haml
%hr{align: "left", width: "500px"}
  - @notifications.each do |n|
    %div{class: "alert alert-block alert-#{n.name} fade in", id: "test"}
      %button.close{"data-dismiss" => "alert", type: "button", }
      = n.msg
      = n.created_at.in_time_zone('Central Time (US & Canada)')
      %div{align: "right", class: "fade in"}
        = link_to 'Delete', notification_path(n), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-mini btn-danger'
#dino
  #footer{align: "center"}
    %a{href: "mailto:Paul.Meier@fisglobal.com"} Contact

app/views/static_pages/reports.haml
.page-header
  %h1 Reports
- @locations.each do |location|
  = report_pill(location)

app/views/static_pages/storageLayout.haml
:javascript
  $(document).ready(function() {
      $('.tip').tooltip();
  });
.page-header
  %h1 Storage Layout
- @machineList.each do |m|
  %br
  %table#minTable{align: "center"}
    %thead
      %tr
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "tooltip", :title => "The IOCDS designated name."}CPU
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "The machines serial number."}Serial
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "The IBM MIPS rating."}MIPS
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "The IBM MSU rating."}MSU
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "Converts MIPS (at the weight value) to MSUs for software contracts."}MSU Weight
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "The IBM designation for the number of z/OS engines."}Capacity
        %th Model
        %th 
          %a{"data-placement" => "top", :href => "#", :rel => "itooltip",  class: "tip",
           :title => "Indicates how much of the logical engines assigned an LPAR are used. (Physical engines are never permanently assigned an LPAR.)"}Per CP Share
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "The standard amount of storage allocated to this machine."}Storage
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "Available storage."}Remaining Storage
      %tbody
        %td= m.name
        %td= m.serialNumber
        %td= m.machineConfig.capacity.mips
        %td= m.machineConfig.capacity.msu
        %td= MachineConfig.msuPerEngine(m.id)
        %td= m.machineConfig.capacity.capSetting
        %td= m.machineConfig.mod.name
        %td= MachineConfig.machineCpPerShare(m.id)
        %td= m.machineConfig.centralStorage
        %td= MachineConfig.remainingStorage(m.id)
  %br
  %table#minTable
    %thead
      %tr
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "LPAR name."}LPAR
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "I/O protocols use this number to direct incoming I/O to the correct LPAR."}Lpar ID
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "This ID is set by the systems group in the SYSNAME parameter of the member IEASYS00 in SYS1.PARMLIB"}SMF ID
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "Except for OVERHEAD, these are the values entered via the HMC (Hardware Management Console)."}Coded Weight
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "Regardless of coded weight values, PR/SM normalizes the weight settings to 100."}Running Weight
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "This column, generated for TAPS, converts MIPS (at the weight value) to MSUs for software contracts."}MSU Weight
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "This is the maximum MIPS that will be allocated to this LPAR when the MACHINE is running at 100%."}Max MIPS (Weight)
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip",
           :title => "If there is no CAP VALUE, this is the maximum MIPS this LPAR could get based on the number of logical engines assigned in the HMC."}Max MIPS Engine Cap
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "This value represents the MAXIMUM MIPS this LPAR can use if neither weight nor capping is a factor."}Max Kick
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "This is the MSU value entered into the HMC that corresponds with the desired MIPS value."}Cap Value
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "These are the values entered via the HMC (Hardware Management Console)."}Ziip Weight
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "These are the values entered via the HMC (Hardware Management Console)."}Zaap Weight
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "The number of Z/OS logical engines assigned to this LPAR. The assignment is done on the HMC console."}Local Engines
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "This entry exists if a zIIP engine(s) is assigned to this LPAR, normally in shared (S) mode."}ZIIPs
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "This entry exists if a zAAP engine(s) is assigned to this LPAR, normally in shared (S) mode."}ZAAPs
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "This entry exists if a IFL engine(s) is assigned to this LPAR."}IFLs
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip",
           :title => "Guaranteed Processor Value. This value is based on weight. When running at 100% GPV shows the number of engines that will be used by this LPAR. WHOLE numbers are preferred! Fractional numbers mean overhead is likely to be higher as Z/OS swaps real engines. Real engine swapping can optionally be minimized via HiperDispatch."}GPV
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "Indicates how much of the logical engines assigned an LPAR are used. (Physical engines are never permanently assigned an LPAR."}Per CP Share
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "The total amount of storage requitred for full CBU mode operation with all LPARs recovered."}Storage CBU
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "The standard amount of storage allocated to this LPAR via the HMC."}Storage Normal
        %th 
          %a{"data-placement" => "top", :href => "#", class: "tip", :rel => "itooltip", :title => "The value coded in the HMC for this parameter."}Reserved Storage
    %tbody
      - m.lpars.find_each(batch_size: 200) do |lpar|
        %tr#lconflist
          %td= lpar.name
          %td= lpar.mid
          %td= lpar.smfid
          %td= lpar.lparConfig.codedWeight
          %td= lpar.lparConfig.runningWeight
          %td= LparConfig.msuWeight(lpar.id)
          %td= LparConfig.maxMips(lpar.id)
          %td= LparConfig.mipsCap(lpar.id)
          %td= LparConfig.maxKick(lpar.id)
          %td= lpar.lparConfig.capValue 
          %td= lpar.lparConfig.ziipWeight
          %td= lpar.lparConfig.zaapWeight
          %td= lpar.lparConfig.localEngines
          %td= lpar.lparConfig.ziip
          %td= lpar.lparConfig.zaap
          %td= lpar.lparConfig.ifl
          %td= LparConfig.gpv(lpar.id)
          %td= LparConfig.perCpShare(lpar.id)
          %td= lpar.lparConfig.storageCbu
          %td= lpar.lparConfig.storageNormal
          %td= lpar.lparConfig.reservedStorage
      %tr
        %td HSA
        %td
        %td   
        %td
        %td
        %td
        %td
        %td
        %td
        %td
        %td
        %td
        %td
        %td
        %td
        %td
        %td
        %td
        %td
        %td
        %td
      %tr
        %td  
        %td 
        %td
        %td= LparConfig.sum(:codedWeight, :conditions => ['lpar_id in (?)', m.lpars.map(&:id)])
        %td= LparConfig.sum(:runningWeight, :conditions => ['lpar_id in (?)', m.lpars.map(&:id)])
        %td
        %td
        %td
        %td
        %td
        %td= LparConfig.sum(:ziipWeight, :conditions => ['lpar_id in (?)', m.lpars.map(&:id)])
        %td
        %td= LparConfig.sum(:localEngines, :conditions => ['lpar_id in (?)', m.lpars.map(&:id)])
        %td
        %td
        %td
        %td
        %td
        %td= LparConfig.sum(:storageCbu, :conditions => ['lpar_id in (?)', m.lpars.map(&:id)])
        %td= LparConfig.sum(:storageNormal, :conditions => ['lpar_id in (?)', m.lpars.map(&:id)])
        %td

app/views/static_pages/ziipreport.haml
.page-header
  %h1 ZIIP Detailed Report
- @machines.each do |m|
  %h3= m.name
  %strong
    Name
  = m.name
  %br
  %strong
    Peak % Used
  = number_to_percentage(Ziip.findBoxPeaks(m.id).peak.to_i.ceil, :precision => 1)
  %br
  %strong
    Peak Time
  = Ziip.findBoxPeaks(m.id).DateTime
  %br
  %strong
    Average CEC ZIIP
  = number_to_percentage(Ziip.findBoxAverage(m.id), :precision => 1)
  %br
  %table#minTable
    %thead
      %tr
        %th LPAR
        %th Peak
        %th Average
    %tbody
      - Ziip.findBoxLPARpeaks(m.id).each do |l|
        %tr
          %td= l.LPAR
          %td= number_to_percentage(l.max.ceil, :precision => 1)
          %td= number_to_percentage(l.average, :precision => 2)
  %br