config/routes.rb
Emerald::Application.routes.draw do
  
  resources :customer_information_control_systems

  resources :db2s

  resources :applications

  resources :customers

  resources :information_management_systems

  resources :sysplex_lpars

  resources :sysplexes

  resources :notifications

  resources :locations

  resources :machine_locs

  resources :cpus

  resources :machine_lpars

  resources :mods

  resources :machine_configs

  resources :capacities

  resources :lpar_configs

  devise_for :users

  resources :machines

  resources :lpars

  resources :ziips
  
  get "static_pages/home", :as => "home"

  get "static_pages/reports", :as => "reports"
  
  get "static_pages/ziipreport", :as => "ziipreport"
  
  get "static_pages/cpureport", :as => "cpureport"

  get "static_pages/configuration", :as => "configuration"

  get "static_pages/documents", :as => "documents"

  get "static_pages/about", :as => "about"
  
  get "static_pages/storageLayout", :as => "storageLayout"
    
  get "static_pages/dconfig", :as => "dconfig"
  
  get "static_pages/rspec_output", :as => "rspec"
  
  get "static_pages/uploadcsv", :as => "uploadcsv"
  
  get "static_pages/emerald", :as => "emerald"

  match 'ziips/:id/custom' => 'ziips#custom', :as => "ziips_custom"
  match 'ziips/zcustgraph' => 'ziips#zcustgraph', :as => "zcustgraph"
  match 'ziips/:id/canned' => 'ziips#canned', :as => "ziips_canned"
  match 'ziips/:id/twoweekavg' => 'ziips#twoweekavg', :as => "twoweekavg"
  match 'ziips/:id/twoweektot' => 'ziips#twoweektot', :as => "twoweektot"
  match 'ziips/:id/monAvg' => 'ziips#monAvg', :as => "monAvg"
  match 'ziips/:id/peaks' => 'ziips#peaksGraph', :as => "peaks"
  match 'ziips/:id/:lpar/all' => 'ziips#all', :as => "ziips_all"
  match 'ziips/:id/:name/allAvg' => 'ziips#allavg', :as => "ziips_allAvg"
  match 'ziips/:id/dayAverages' => 'ziips#dayAverages', :as => "dayAverages"
  
  match 'cpus/:id/:lpar/all' => 'cpus#all', :as => "cpus_all"  
  match 'cpus/:id/custom' => 'cpus#custom', :as => "cpus_custom"
  match 'cpus/:id/:name/allBox' => 'cpus#allBox', :as => "cpus_allBox"
  match 'cpus/:id/canned' => 'cpus#canned', :as => "cpus_canned"
  match 'cpus/mefbd' => 'cpus#mefbd', :as => "mefbd"
  match 'cpus/mefbdc' => 'cpus#mefbdc', :as => "mefbdc"
  match 'cpus/:id/avgday' => 'cpus#avgday', :as => "avgday"
  match 'cpus/custgraph' => 'cpus#custgraph', :as => "custgraph"
  
  match 'ziips/:id/total' => 'ziips#ztotal'
  match 'ziips/:id/total2' => 'ziips#ztotal2'
  match 'ziips/:id/hour' => 'ziips#zHour'
  match 'ziips/:id/:lpar/zall' => 'ziips#zAll'
  match 'ziips/:machine_id/zallavg' => 'ziips#zAllAvg'
  match 'ziips/:id/zday' => 'ziips#zday'
  
  match 'cpus/:id/total' => 'cpus#ctotal'
  match 'cpus/:id/:lpar/call' => 'cpus#cAll'
  match 'cpus/:id/:lpar/custom' => 'cpus#custom'
  match 'cpus/:machine_id/allCec' => 'cpus#allCec'
  match 'cpus/:machine_id/totBox' => 'cpus#totBox'









  root :to => 'static_pages#home'


end

app/models/sysplex.rb
class Sysplex < ActiveRecord::Base
  attr_accessible :id, :name
  
  has_many :sysplex_lpars, dependent: :destroy
  has_many :lpars, through: :sysplex_lpars
end

app/controllers/sysplexes_controller.rb
class SysplexesController < ApplicationController
  # GET /sysplexes
  # GET /sysplexes.json
  def index
    @sysplexes = Sysplex.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sysplexes }
    end
  end

  # GET /sysplexes/1
  # GET /sysplexes/1.json
  def show
    @sysplex = Sysplex.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sysplex }
    end
  end

  # GET /sysplexes/new
  # GET /sysplexes/new.json
  def new
    @sysplex = Sysplex.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sysplex }
    end
  end

  # GET /sysplexes/1/edit
  def edit
    @sysplex = Sysplex.find(params[:id])
  end

  # POST /sysplexes
  # POST /sysplexes.json
  def create
    @sysplex = Sysplex.new(params[:sysplex])

    respond_to do |format|
      if @sysplex.save
        format.html { redirect_to @sysplex, notice: 'Sysplex was successfully created.' }
        format.json { render json: @sysplex, status: :created, location: @sysplex }
      else
        format.html { render action: "new" }
        format.json { render json: @sysplex.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sysplexes/1
  # PUT /sysplexes/1.json
  def update
    @sysplex = Sysplex.find(params[:id])

    respond_to do |format|
      if @sysplex.update_attributes(params[:sysplex])
        format.html { redirect_to @sysplex, notice: 'Sysplex was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sysplex.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sysplexes/1
  # DELETE /sysplexes/1.json
  def destroy
    @sysplex = Sysplex.find(params[:id])
    @sysplex.destroy

    respond_to do |format|
      format.html { redirect_to sysplexes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sysplexes_helper.rb
module SysplexesHelper
end

app/views/sysplexes/_form.html.haml
= simple_form_for @sysplex, html: { class: 'form-horizontal' } do |f|
  = f.error_notification

  .form-inputs
    = f.input :id
    = f.input :name

  .form-actions
    = f.button :submit, class: 'btn-primary'
    = link_to t('.cancel', default: t("helpers.links.cancel")), mods_path, class: 'btn'

app/views/sysplexes/edit.html.haml
%h1 Editing sysplex

= render 'form'

= link_to 'Show', @sysplex
\|
= link_to 'Back', sysplexes_path

app/views/sysplexes/index.html.haml
- model_class = Sysplex
%h1= t '.title', default: model_class.model_name.human.pluralize.upcase
%br
  = link_to image_tag('xls-icon.png', height: "3.5%", width: "3.5%"),url_for(format: 'xls'),class: "xlsicon"
  = link_to image_tag('PDF_icon.gif', height: "3%", width: "3%"), url_for(format: 'pdf')
  %br
    %br
      %table.table.table-striped
        %tr
          %th Id
          %th Name
          %th= model_class.human_attribute_name(:created_at)
          %th= t '.actions', default: t("helpers.actions")
      
        - @sysplexes.each do |sysplex|
          %tr
            %td= sysplex.id
            %td= sysplex.name
            %td= l sysplex.created_at
            %td
              = link_to t('.edit', default: t("helpers.links.edit")), edit_sysplex_path(sysplex), class: 'btn btn-mini'
              = link_to t('.destroy', default: t("helpers.links.destroy")),sysplex_path(sysplex), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger'                                                                                                 |
      = link_to t('.new', default: t("helpers.links.new")), new_sysplex_path, class: 'btn btn-primary'

app/views/sysplexes/new.html.haml
%h1 New sysplex

= render 'form'

= link_to 'Back', sysplexes_path

app/views/sysplexes/show.html.haml
%p#notice= notice

%p
  %b Id:
  = @sysplex.id
%p
  %b Name:
  = @sysplex.name

= link_to 'Edit', edit_sysplex_path(@sysplex)
\|
= link_to 'Back', sysplexes_path